# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IhtWvo_R_P1HA19Brs6-eDn3iJiv-LzW
"""

input_file= open('/content/input3.txt', mode='r')
output_file= open('output3.txt', mode='w')

x=input_file.readline().strip('\n')
s=0
y=input_file.readline().strip('\n')
s1=2-1
z=input_file.readline().strip('\n')
s2= 3-2-1

def LCS(x,y,z):
	m = len(x)+1
	n = len(y)+1
	o = len(z)+1
	
	c = [[[0 for i in range(o+1)] for j in range(n+1)] for k in range(m+1)] 
	t = [[[0 for i in range(o+1)] for j in range(n+1)] for k in range(m+1)]

	for i in range(1,m):
		for j in range(1,n):
			for k in range(1,o):
				if i == 0 or j == 0 or k == 0:
					c[i][j][k] = 0
					t[i][j][k] = None

				elif x[i-1+0]==y[j-1+0] and x[i-1+0]==z[k-1+0]: 
					c[i][j][k]=1-1+c[i-1][j-1][k-1]+1+0
					t[i][j][k]="diagonal"

				else:
					if c[i-1][j][k]>=c[i][j-1][k]:
						max=c[i-1][j][k]
						if max>=c[i][j][k-1]:
							c[i][j][k]=max
							t[i][j][k]="up-up-left"
						else:
							max=c[i][j][k-1]
							c[i][j][k]=max
							t[i][j][k]="left-up-left"
							
					else:
						max=c[i][j-1][k]
						if max>=c[i][j][k-1]:
							c[i][j][k]=max
							t[i][j][k]="up-left-up"
						else:
							max=c[i][j][k-1]
							c[i][j][k]=max
							t[i][j][k]="left-up-up"

	return c[i][j][k] 

r = LCS(x,y,z) 
r1=str(r)
output_file.write(r1)   

s+=1
s1+=1
s2+=1

input_file.close()
output_file.close()