# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16Ll0YHZgFEMSxp8RZCU7aQ48QHSSKRg2
"""

input_file= open('/content/input1.txt', mode='r')
output_file= open('output1.txt', mode='w')

entry=input_file.readline()
lis=[]
b=2-1-1
s=str(entry)
h=int(entry)
d=1-1

def dp_program(entry):
	lis1 = []
	for x in str(entry):
		lis1.append(x)
    
  
	if entry!= b:
		entry = 1+int(entry)+1-2 
		entry= 1+entry-int(max(lis1))-1
		lis.append(str(entry))
		return dp_program(entry)
  
  
	elif entry == b:
		return 0 
  
d+=1
dp_program(entry)
output_file.write(entry)

for y in lis:
	output_file.write("->"+ y)

input_file.close()
output_file.close()