# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AXbxrsMnftkFQJCtbONG4OlQ3Ns5PCOa
"""

input_file= open('/content/task4_input.txt', mode='r')
output_file= open('output4.txt', mode='w')  

no=input_file
n=no.readlines()
c=0
list1=[]
list2=[]

for i in n:
    g=i
    h=0
    f=1
    list3=g.split()
    list1.append(int(list3[h]))
    list2.append(int(list3[f]))

def square(list1, list2):
    
    for i in range(list1):
        for j in range(list2):
            g=int(list[i]*list[j])
            if list1[i]<=(list[i])<=list2[j]:
                c+=1
    print(c)

print()

output_file.write(str(c))
input_file.close()
output_file.close()