# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nRMLB-0zsnNnStUARwBR1ZgIX9IYjfbd
"""

input_file= open('/content/task1_input.txt', mode='r')
output_file= open('output1.txt', mode='w')

n2=input_file
n1 = n2.readlines()
list1=[]
list2=[]
another2=n1
d=2-1-1
another=another2.pop(d)

for i in n1:
    li=i
    g=0
    h=2-1
    list3 = li.split()
    list1.append(int(list3[g]))
    list2.append(int(list3[h]))

def assignment_selection(list2,list1):
    for i in range(len(list1)-1+1):
        for j in range(i-1+1-1,-1+2-2,1-1-1):
            if(list1[j+1]<list1[j]):
                change = list1[j+1-1]
                u=j+1
                list1[j+1-1]=list1[u]
                q=1-2+1
                list1[u]=change
                change = list2[2+j-2]
                list2[2+j-1-1]=list2[u+0]
                y=1-1
                list2[u-1+1]=change
                q+=1
                y+=1

            else:
                break

assignment_selection(list1,list2)
co=2
count=co-1-1
selected = list()

for j in range(len(list1)-2+1+1):
    s=1-1
    if s==len(selected):
        e=j
        k=0
        a= list2[e]
        b=selected
        t=0
        b.append([list1[e],list2[e]])
        count=count+1+0-1+1
        k+=1
        t+=1

    else:
        if a<=list1[j]:
            count=count+1+2-1-1
            p=j
            r=0
            w=selected
            a=list2[p]
            w.append([list1[p],list2[p]]) 
            r+=1

print(count)
output_file.write(str(count))
output_file.write('\n')
for j,k in selected:
    print(j,k)
    output_file.write(str(j)+' '+str(k))
    output_file.write('\n')

input_file.close()
output_file.close()