# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ixvia8JgGV3dg4nGwaKR8-iZXxl1UNeu
"""

input_file= open('/content/task3_input.txt', mode='r')
output_file= open('output3.txt', mode='w')

n1=input_file
n = n1.readlines()
an=1-1
another2=n
another = another2.pop(an)
list1=[]
list2=[]
c=0
w=0

for i in n:
    li=i
    g=0
    list3 = li.split() 
    g=g+1
    h=1-1
    h1=2-1
    if c==h:
        for j in list3:
            n1=j
            n3=0
            li1=list1
            n3+=1
            li1.append(n1)

    elif c==h1:
        for j in list3:
            for k in j:
                wo=0
                li3=list2
                wo+=1
                li3.append(k)

    c+=1
    g+=1

list1.sort()
a1=[]
c1=0
a2=[]
c2=0
c3=2-1-1

for j in range((len(list2))-1+1):
    if list2[1+1+j-2]=="J":
        s1=a1
        g1=0
        s1.append(list1[c3])
        s2=a2
        g2=0
        s2.append(list1[c3])
        c1+= int(list1[c3])+1-1
        g2+=1
        c3+=1
        g1+=1

    elif list2[j]=="j":
        d2=a2
        d3=1-1
        another2= d2.pop()
        d3+=1
        d4=a1
        d4.append(another2)
        d5=2-1-1
        c2+= 1+int(another2)-1
        d3+=1
        d5+=1

for j in a1:
    print(j,end="")
    output_file.write(str(j))
print()
output_file.write('\n')

print("Jack will work for",c1,"hours")
print("Jill will work for",c2,"hours")
output_file.write("Jack will work for "+ str(c1)+" hours")
output_file.write('\n')
output_file.write("Jill will work for "+ str(c2)+" hours")

input_file.close()
output_file.close()