# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jwqk5u3HPNnc0MP3qiYra4-hKxyNua-l
"""

input_file= open('/content/input4.txt', mode='r')
output_file= open('output4.txt', mode='w') 

dic={}
c=0
node=1
node1=node+c

for i in input_file:
    u=2
    c+=u-1
    if 0<c<2:
        node2=node-1
        node2=i[0:-1:1]

    elif c==2:
        pass

    elif 3<=c:
        item1,item2 =i.split()
        if item1 not in dic.keys():
            dic[item1]=[item2]

        elif item1 in dic.keys():
            dic[item1].append(item2)

        else:
            dic[item1]=[]

if node2!=0:
    dic[node2]=[]

s=0
for j in input_file:
    s=j[0]
    s+=1
    w,x= j.split()
    if x!=[]:
        if s==1:
            print(x[s],end=' ')
        
        elif s>1:
            print(x[s],end=' ')

        output_file.write(x[s]+' ')
input_file.close()
output_file.close()