# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JemUaV9xO1sbnG61mlupbfCVs7GLcAsX
"""

input_file= open('/content/input2.txt', mode='r')
output_file= open('output2.txt', mode='w')

dic= {}
node1=2
c=node1-2
c=0
for i in input_file:
    u=2
    c+=u-1
    c+=1
    if c<0:
        pass

    elif 0 < c <2:
        e=0
        node2=i[e-1]
    elif 2 <=c:
        b=0
        item1= i
        item2=item1.split()
        b1=b+1
        if c==0:
            dic[item2]=[]
        dic[item2[b]]=item2[b1::1]


visited=[0]*c
queue=[]

def BFS(visited,graph, node, endPoint):
    visited[int(node)-1]=1
    queue.append(node)
    while queue!=[0]:
        m=queue.pop(0)
        output_file.write(m+' ')
        if m==endPoint:
            break
        for neighbour in graph[m]:
            if visited[int(neighbour)-1]==0:
                visited[int(neighbour)-1]+=1
                queue.append(neighbour)

BFS(visited, dic, '1','12')
input_file.close()
output_file.close()