# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zQshSYlxMsIpgFBFcnHxs4cMOpd1enJE
"""

input_file= open('/content/input1.txt', mode='r')
output_file= open('output1.txt', mode='w')

dic= {}
c=0
node=1
node1=node+c

for i in input_file:
    u=2
    c+=u-1
    if 0<c<2:
        node2=node-1
        node2=i[0:-1:1]

    elif c==2:
        pass
    
    elif 3<=c:
        item1, item2= i.split()
        if item1 not in dic.keys():
            dic[item1]=[item2]

        elif item1 in dic.keys():    
            dic[item1].append(item2)

        else:
            dic[item1]=[]

if node2!=0:
    dic[node2]=[]

output_file.write(node2)
output_file.write('\n')

variable=0

for item1,item2 in dic.items():
    output_file.write(item1)
    output_file.write('    ')

    for d in range(variable, len(item2)):
        if d<len(item2):
            output_file.write(item2[d])
            output_file.write('    ')

    output_file.write('\n')

input_file.close()
output_file.close()